# Generated by Django 3.1.4 on 2023-05-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monety_sklep', '0002_coin_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coin',
            name='year',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
