# Generated by Django 3.1.4 on 2023-05-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monety_sklep', '0003_auto_20230507_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='price',
            field=models.IntegerField(),
        ),
    ]
