# Generated by Django 3.1.4 on 2023-05-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monety_sklep', '0004_auto_20230507_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='coin',
            name='year',
            field=models.IntegerField(),
        ),
    ]
