# Generated by Django 3.1.4 on 2023-05-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('taken', models.BooleanField()),
                ('year', models.FloatField()),
                ('total', models.FloatField()),
                ('description', models.CharField(max_length=40000)),
                ('picture_url', models.CharField(default='', max_length=2083)),
            ],
        ),
    ]
