# Generated by Django 3.1.4 on 2023-05-07 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monety_katalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coin',
            new_name='Coin_katal',
        ),
    ]
