# Generated by Django 3.1.4 on 2023-05-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monety_katalog', '0002_auto_20230507_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin_katal',
            name='year',
            field=models.IntegerField(),
        ),
    ]
